name: dart_phonetics
description: A collection of phonetic algorithms. These algorithms help find words or names that sound similar by generating an encoding that can be compared or indexed for fuzzy searching.
version: 1.0.1
homepage: https://github.com/raycardillo/dart_phonetics
repository: https://github.com/raycardillo/dart_phonetics

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  charcode: ^1.3.1

dev_dependencies:
  test: ^1.17.8
  lints: ^1.0.1
